### ISSUE TITLE
Logo for RxBattery

### ISSUE THREAD

**Issue by ghost** [pwittchen/RxBattery#1]
I ran into your project while you were walking around Github. I design a logo for open source projects to do things I can put in sites like Dribbble, Behance. I can design a Logo for you if you want. What kind of Logo do you want? What are the benefits of the program? What are your favorite logo samples?

If you say these, I can design a logo for you.

**Comment by pwittchen** [comment]
Hi,

Thanks for your message. I published this project about an hour ago or something like that, so you're fast :-D.

> What are the benefits of the program?

It's a simple library written in Kotlin language with RxJava and RxKotlin libraries, which you can plug into the Android application and monitor the battery state of the device (e.g. status, battery level, plugged status, battery health and so on).

You can design a logo. I really appreciate that initiative. If your design will be nice, neat and simple, I'll add the logo to my project.

Cheers!

Piotr

**Comment by ghost** [comment]
![rxbatter](https://user-images.githubusercontent.com/36993664/44373134-5df14780-a4f0-11e8-9259-ced5c6617338.jpg)

* R and Energy, Battery icon combined.

**Comment by pwittchen** [comment]
Wow! That's a great logo! Thanks a lot. I'll add it to the project soon.
All looks very good. I think I like version 5 the most.

**Comment by pwittchen** [comment]
I've added the logo to `README.md` and mentioned you in the [Credits](https://github.com/pwittchen/RxBattery#credits) section.

Thanks again!

Cheers,
Piotr

**Comment by ghost** [comment]
Thank you for accepting. In the link below; logo, logotype and icon's high resolution svg and png files. If you think it's a missing file, you can write to me. 

https://drive.google.com/open?id=1ACPNtRz81qk1Ht_F1bGKjdOTBVf8pi2c

Cheers,

**Comment by pwittchen** [comment]
Thanks! I'll update logo with higher resolution image.
