### ISSUE TITLE
Leaked IntentReciever.

### ISSUE THREAD

**Issue by xsahil03x** [pwittchen/RxBattery#5]
Missing a call to unregisterReceiver();

**Comment by pwittchen** [comment]
Thanks for reporting this issue, but it's here: https://github.com/pwittchen/RxBattery/blob/master/library/src/main/kotlin/com/github/pwittchen/rxbattery/library/RxBattery.kt#L39

Are you able to reproduce the case with memory leak with concrete steps?

**Comment by pwittchen** [comment]
There are no further comments, so I'm closing this issue as invalid.
