### ISSUE TITLE
How to stop it?

### ISSUE THREAD

**Issue by RHSaliya** [pwittchen/RxBattery#63]
I want to stop RxBattery programmatically after the activity is paused or destroyed

**Comment by pwittchen** [comment]
You can just dispose flowable with dispose() method in onPause() method of
the Activity just like every other flowable.

--
Piotr Wittchen,
http://wittchen.io

czw., 16 lip 2020, 06:31 użytkownik RHSaliya <notifications@github.com>
napisał:
